### PR TITLE
bunch of changes

### PR DESCRIPTION
**Pull request by MemeHoovy**
removed useless files
cleaned up project.xml & some code
in general, removed a bunch of useless things

### CODE REVIEW

**Comment by Aly-Ant0** [comment]
you delete some important stuff

**Comment by MemeHoovy** [comment]
> you delete some important stuff

they weren't really important

**Comment by MemeHoovy** [comment]
ok now I see what you meant

**Comment by MemeHoovy** [comment]
:(

**Comment by Aly-Ant0** [comment]
i will remove this theese useless things in the release

**Comment by MemeHoovy** [comment]
> i will remove this theese useless things in the release

so I made this PR too early apparently

**Comment by Aly-Ant0** [comment]
yea

**Comment by MemeHoovy** [comment]
> yea

😐

**Pull request closed without merging**
